server:
  port: 8002

# mybaits配置
mybatis:
  type-aliases-package: com.lemon.springcloud.pojo
  mapper-locations: classpath:mapper/*.xml

# spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#Eureka 配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8002

#info配置
info:
  app.name: lemon-springcloud
  company.name: blog.lemon.springcloud