server:
  port: 3344

spring:
  application:
    name: springcloud-config-server-3344
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ningmengbukaixin/SpringCloud-Config-Demo.git